version: 0.2
env:
  variables:
    S3_BUCKET: "negi-mern-todo-frontend-demo"
    CLOUDFRONT_DIST_ID: "E1PF3QW3K4MLZ1"

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies
      - npm ci
  build:
    commands:
      - echo Building React app
      - npm run build
  post_build:
    commands:
      - echo Deploying to S3
      # Upload index.html with no-cache
      - aws s3 cp build/index.html s3://$S3_BUCKET/index.html --cache-control "no-cache, no-store, must-revalidate"
      # Upload all other files with long cache
      - aws s3 sync build/ s3://$S3_BUCKET --delete --exclude "index.html" --cache-control "max-age=31536000, public"
      # Invalidate CloudFront so new index.html is served
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DIST_ID --paths "/*"
